# Generated by Django 5.2.1 on 2025-05-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_payment_id_alter_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
