# Generated by Django 5.2.1 on 2025-05-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
