# Generated by Django 5.2.1 on 2025-05-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
    ]
